GET http://localhost:3030/authors

####
POST http://localhost:3030/createAuthor
Content-Type: application/json

{
    "firstName": "Marco",
    "lastName": "Santoro",
    "email": "marcosantoro@gmail.com",
    "birthday": "05.01.1999",
    "avatar": "?"
}